# Generated by Django 2.0.5 on 2018-05-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_article_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
